name: 'publish'
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/Transmitter/.cache/pip
            ~/Transmitter/.platformio/.cache
            ~/Reciever/.cache/pip
            ~/Reciever/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core - Reciever
        working-directory: ./Reciever
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project - Reciever
        working-directory: ./Reciever
        run: pio run
        
      - name: Rename firmware.bin to receiver.bin
        working-directory: ./Reciever
        run: mv .pio/build/heltec_wifi_lora_32_V2/firmware.bin .pio/build/heltec_wifi_lora_32_V2/receiver.bin
        
      - name: Install PlatformIO Core - Transmitter
        working-directory: ./Transmitter
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project - Transmitter
        working-directory: ./Transmitter
        run: pio run
        
      - name: Rename firmware.bin to transmitter.bin
        working-directory: ./Transmitter
        run: mv .pio/build/heltec_wifi_lora_32_V2/firmware.bin .pio/build/heltec_wifi_lora_32_V2/transmitter.bin
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./Reciever/.pio/build/heltec_wifi_lora_32_V2/receiver.bin
            ./Transmitter/.pio/build/heltec_wifi_lora_32_V2/transmitter.bin
