name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/Transmitter/.cache/pip
            ~/Transmitter/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/cache@v3
        with:
          path: |
            ~/Reciever/.cache/pip
            ~/Reciever/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core - Reciever
        working-directory: ./Reciever
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project - Reciever
        working-directory: ./Reciever
        run: pio run
        
      - name: Install PlatformIO Core - Transmitter
        working-directory: ./Transmitter
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project - Transmitter
        working-directory: ./Transmitter
        run: pio run
